/*
fansi is a fansiterm/tiles.FontTileSet, implementing tiles.Tiler. It is made from the png images
present in this source directory. This is the default altCharSet for fansiterm. The FontTileSet
can be regenerated by running 'go generate' in this directory. The generating program looks for
png files in the directory and then uses the first unicode character of the filename to identify
the rune in the FontTileSet. Adding or replacing glyphs is as simple as adding or change the png
files in this directory and re-running 'go generate'.
*/
package fansi // import "github.com/sparques/fansiterm/tiles/fansi"
